/* 
 * The SMS Works API
 *
 * The SMS Works provides a low-cost, reliable SMS API for developers. Pay only for delivered texts, all failed messages are refunded.
 *
 * OpenAPI spec version: 1.1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing CreditsResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class CreditsResponseTests
    {
        // TODO uncomment below to declare an instance variable for CreditsResponse
        //private CreditsResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CreditsResponse
            //instance = new CreditsResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CreditsResponse
        /// </summary>
        [Test]
        public void CreditsResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" CreditsResponse
            //Assert.IsInstanceOfType<CreditsResponse> (instance, "variable 'instance' is a CreditsResponse");
        }


        /// <summary>
        /// Test the property 'Credits'
        /// </summary>
        [Test]
        public void CreditsTest()
        {
            // TODO unit test for the property 'Credits'
        }

    }

}
