/* 
 * The SMS Works API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing MessagesResponseMessages
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class MessagesResponseMessagesTests
    {
        // TODO uncomment below to declare an instance variable for MessagesResponseMessages
        //private MessagesResponseMessages instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of MessagesResponseMessages
            //instance = new MessagesResponseMessages();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of MessagesResponseMessages
        /// </summary>
        [Test]
        public void MessagesResponseMessagesInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" MessagesResponseMessages
            //Assert.IsInstanceOfType<MessagesResponseMessages> (instance, "variable 'instance' is a MessagesResponseMessages");
        }

        /// <summary>
        /// Test the property 'Schema'
        /// </summary>
        [Test]
        public void SchemaTest()
        {
            // TODO unit test for the property 'Schema'
        }

    }

}
