/* 
 * The SMS Works API
 *
 * The SMS Works provides a low-cost, reliable SMS API for developers. Pay only for delivered texts, all failed messages are refunded.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing MessageResponseFailurereason
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class MessageResponseFailurereasonTests
    {
        // TODO uncomment below to declare an instance variable for MessageResponseFailurereason
        //private MessageResponseFailurereason instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of MessageResponseFailurereason
            //instance = new MessageResponseFailurereason();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of MessageResponseFailurereason
        /// </summary>
        [Test]
        public void MessageResponseFailurereasonInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" MessageResponseFailurereason
            //Assert.IsInstanceOfType<MessageResponseFailurereason> (instance, "variable 'instance' is a MessageResponseFailurereason");
        }


        /// <summary>
        /// Test the property 'Code'
        /// </summary>
        [Test]
        public void CodeTest()
        {
            // TODO unit test for the property 'Code'
        }
        /// <summary>
        /// Test the property 'Details'
        /// </summary>
        [Test]
        public void DetailsTest()
        {
            // TODO unit test for the property 'Details'
        }
        /// <summary>
        /// Test the property 'Permanent'
        /// </summary>
        [Test]
        public void PermanentTest()
        {
            // TODO unit test for the property 'Permanent'
        }

    }

}
