/* 
 * The SMS Works API
 *
 * The SMS Works provides a low-cost, reliable SMS API for developers. Pay only for delivered texts, all failed messages are refunded.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing QueryMetadata
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class QueryMetadataTests
    {
        // TODO uncomment below to declare an instance variable for QueryMetadata
        //private QueryMetadata instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of QueryMetadata
            //instance = new QueryMetadata();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of QueryMetadata
        /// </summary>
        [Test]
        public void QueryMetadataInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" QueryMetadata
            //Assert.IsInstanceOfType<QueryMetadata> (instance, "variable 'instance' is a QueryMetadata");
        }


        /// <summary>
        /// Test the property 'Schema'
        /// </summary>
        [Test]
        public void SchemaTest()
        {
            // TODO unit test for the property 'Schema'
        }

    }

}
