/* 
 * The SMS Works API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing ScheduledMessageResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ScheduledMessageResponseTests
    {
        // TODO uncomment below to declare an instance variable for ScheduledMessageResponse
        //private ScheduledMessageResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ScheduledMessageResponse
            //instance = new ScheduledMessageResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ScheduledMessageResponse
        /// </summary>
        [Test]
        public void ScheduledMessageResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ScheduledMessageResponse
            //Assert.IsInstanceOfType<ScheduledMessageResponse> (instance, "variable 'instance' is a ScheduledMessageResponse");
        }

        /// <summary>
        /// Test the property 'Messageid'
        /// </summary>
        [Test]
        public void MessageidTest()
        {
            // TODO unit test for the property 'Messageid'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Test]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }

    }

}
