/* 
 * The SMS Works API
 *
 * The SMS Works provides a low-cost, reliable SMS API for developers. Pay only for delivered texts, all failed messages are refunded.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using RestSharp;
using IO.Swagger.Client;
using IO.Swagger.Model;

namespace IO.Swagger.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IBatchMessagesApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Cancels a scheduled SMS message
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="batchid">The ID of the batch you would like returned</param>
        /// <returns>CancelledMessageResponse</returns>
        CancelledMessageResponse CancelScheduledBatchJob (string batchid);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Cancels a scheduled SMS message
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="batchid">The ID of the batch you would like returned</param>
        /// <returns>ApiResponse of CancelledMessageResponse</returns>
        ApiResponse<CancelledMessageResponse> CancelScheduledBatchJobWithHttpInfo (string batchid);
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Retrieve all messages in a batch with the given batch ID
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="batchid">The ID of the batch you would like returned</param>
        /// <returns>MessagesResponse</returns>
        MessagesResponse GetBatchById (string batchid);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Retrieve all messages in a batch with the given batch ID
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="batchid">The ID of the batch you would like returned</param>
        /// <returns>ApiResponse of MessagesResponse</returns>
        ApiResponse<MessagesResponse> GetBatchByIdWithHttpInfo (string batchid);
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Schedules a batch of SMS messages to be sent at the date time you specify
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="smsMessage">Message properties</param>
        /// <returns>ScheduledBatchResponse</returns>
        ScheduledBatchResponse ScheduleBatch (BatchMessage smsMessage);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Schedules a batch of SMS messages to be sent at the date time you specify
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="smsMessage">Message properties</param>
        /// <returns>ApiResponse of ScheduledBatchResponse</returns>
        ApiResponse<ScheduledBatchResponse> ScheduleBatchWithHttpInfo (BatchMessage smsMessage);
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Send a single SMS message to multiple recipients
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="smsMessage">Message properties</param>
        /// <returns>BatchMessageResponse</returns>
        BatchMessageResponse SendBatch (BatchMessage smsMessage);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Send a single SMS message to multiple recipients
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="smsMessage">Message properties</param>
        /// <returns>ApiResponse of BatchMessageResponse</returns>
        ApiResponse<BatchMessageResponse> SendBatchWithHttpInfo (BatchMessage smsMessage);
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Cancels a scheduled SMS message
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="batchid">The ID of the batch you would like returned</param>
        /// <returns>Task of CancelledMessageResponse</returns>
        System.Threading.Tasks.Task<CancelledMessageResponse> CancelScheduledBatchJobAsync (string batchid);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Cancels a scheduled SMS message
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="batchid">The ID of the batch you would like returned</param>
        /// <returns>Task of ApiResponse (CancelledMessageResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<CancelledMessageResponse>> CancelScheduledBatchJobAsyncWithHttpInfo (string batchid);
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Retrieve all messages in a batch with the given batch ID
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="batchid">The ID of the batch you would like returned</param>
        /// <returns>Task of MessagesResponse</returns>
        System.Threading.Tasks.Task<MessagesResponse> GetBatchByIdAsync (string batchid);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Retrieve all messages in a batch with the given batch ID
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="batchid">The ID of the batch you would like returned</param>
        /// <returns>Task of ApiResponse (MessagesResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<MessagesResponse>> GetBatchByIdAsyncWithHttpInfo (string batchid);
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Schedules a batch of SMS messages to be sent at the date time you specify
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="smsMessage">Message properties</param>
        /// <returns>Task of ScheduledBatchResponse</returns>
        System.Threading.Tasks.Task<ScheduledBatchResponse> ScheduleBatchAsync (BatchMessage smsMessage);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Schedules a batch of SMS messages to be sent at the date time you specify
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="smsMessage">Message properties</param>
        /// <returns>Task of ApiResponse (ScheduledBatchResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<ScheduledBatchResponse>> ScheduleBatchAsyncWithHttpInfo (BatchMessage smsMessage);
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Send a single SMS message to multiple recipients
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="smsMessage">Message properties</param>
        /// <returns>Task of BatchMessageResponse</returns>
        System.Threading.Tasks.Task<BatchMessageResponse> SendBatchAsync (BatchMessage smsMessage);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Send a single SMS message to multiple recipients
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="smsMessage">Message properties</param>
        /// <returns>Task of ApiResponse (BatchMessageResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<BatchMessageResponse>> SendBatchAsyncWithHttpInfo (BatchMessage smsMessage);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class BatchMessagesApi : IBatchMessagesApi
    {
        private IO.Swagger.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="BatchMessagesApi"/> class.
        /// </summary>
        /// <returns></returns>
        public BatchMessagesApi(String basePath)
        {
            this.Configuration = new Configuration { BasePath = basePath };

            ExceptionFactory = IO.Swagger.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="BatchMessagesApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public BatchMessagesApi(Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = IO.Swagger.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public IO.Swagger.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public IDictionary<String, String> DefaultHeader()
        {
            return new ReadOnlyDictionary<string, string>(this.Configuration.DefaultHeader);
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        ///  Cancels a scheduled SMS message
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="batchid">The ID of the batch you would like returned</param>
        /// <returns>CancelledMessageResponse</returns>
        public CancelledMessageResponse CancelScheduledBatchJob (string batchid)
        {
             ApiResponse<CancelledMessageResponse> localVarResponse = CancelScheduledBatchJobWithHttpInfo(batchid);
             return localVarResponse.Data;
        }

        /// <summary>
        ///  Cancels a scheduled SMS message
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="batchid">The ID of the batch you would like returned</param>
        /// <returns>ApiResponse of CancelledMessageResponse</returns>
        public ApiResponse< CancelledMessageResponse > CancelScheduledBatchJobWithHttpInfo (string batchid)
        {
            // verify the required parameter 'batchid' is set
            if (batchid == null)
                throw new ApiException(400, "Missing required parameter 'batchid' when calling BatchMessagesApi->CancelScheduledBatchJob");

            var localVarPath = "/batches/schedule/{batchid}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json;charset=UTF-8"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (batchid != null) localVarPathParams.Add("batchid", Configuration.ApiClient.ParameterToString(batchid)); // path parameter

            // authentication (JWT) required
            if (!String.IsNullOrEmpty(Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.DELETE, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("CancelScheduledBatchJob", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<CancelledMessageResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (CancelledMessageResponse) Configuration.ApiClient.Deserialize(localVarResponse, typeof(CancelledMessageResponse)));
        }

        /// <summary>
        ///  Cancels a scheduled SMS message
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="batchid">The ID of the batch you would like returned</param>
        /// <returns>Task of CancelledMessageResponse</returns>
        public async System.Threading.Tasks.Task<CancelledMessageResponse> CancelScheduledBatchJobAsync (string batchid)
        {
             ApiResponse<CancelledMessageResponse> localVarResponse = await CancelScheduledBatchJobAsyncWithHttpInfo(batchid);
             return localVarResponse.Data;

        }

        /// <summary>
        ///  Cancels a scheduled SMS message
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="batchid">The ID of the batch you would like returned</param>
        /// <returns>Task of ApiResponse (CancelledMessageResponse)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<CancelledMessageResponse>> CancelScheduledBatchJobAsyncWithHttpInfo (string batchid)
        {
            // verify the required parameter 'batchid' is set
            if (batchid == null)
                throw new ApiException(400, "Missing required parameter 'batchid' when calling BatchMessagesApi->CancelScheduledBatchJob");

            var localVarPath = "/batches/schedule/{batchid}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json;charset=UTF-8"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (batchid != null) localVarPathParams.Add("batchid", Configuration.ApiClient.ParameterToString(batchid)); // path parameter

            // authentication (JWT) required
            if (!String.IsNullOrEmpty(Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.DELETE, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("CancelScheduledBatchJob", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<CancelledMessageResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (CancelledMessageResponse) Configuration.ApiClient.Deserialize(localVarResponse, typeof(CancelledMessageResponse)));
        }

        /// <summary>
        ///  Retrieve all messages in a batch with the given batch ID
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="batchid">The ID of the batch you would like returned</param>
        /// <returns>MessagesResponse</returns>
        public MessagesResponse GetBatchById (string batchid)
        {
             ApiResponse<MessagesResponse> localVarResponse = GetBatchByIdWithHttpInfo(batchid);
             return localVarResponse.Data;
        }

        /// <summary>
        ///  Retrieve all messages in a batch with the given batch ID
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="batchid">The ID of the batch you would like returned</param>
        /// <returns>ApiResponse of MessagesResponse</returns>
        public ApiResponse< MessagesResponse > GetBatchByIdWithHttpInfo (string batchid)
        {
            // verify the required parameter 'batchid' is set
            if (batchid == null)
                throw new ApiException(400, "Missing required parameter 'batchid' when calling BatchMessagesApi->GetBatchById");

            var localVarPath = "/batch/{batchid}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json;charset=UTF-8"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (batchid != null) localVarPathParams.Add("batchid", Configuration.ApiClient.ParameterToString(batchid)); // path parameter

            // authentication (JWT) required
            if (!String.IsNullOrEmpty(Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetBatchById", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<MessagesResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (MessagesResponse) Configuration.ApiClient.Deserialize(localVarResponse, typeof(MessagesResponse)));
        }

        /// <summary>
        ///  Retrieve all messages in a batch with the given batch ID
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="batchid">The ID of the batch you would like returned</param>
        /// <returns>Task of MessagesResponse</returns>
        public async System.Threading.Tasks.Task<MessagesResponse> GetBatchByIdAsync (string batchid)
        {
             ApiResponse<MessagesResponse> localVarResponse = await GetBatchByIdAsyncWithHttpInfo(batchid);
             return localVarResponse.Data;

        }

        /// <summary>
        ///  Retrieve all messages in a batch with the given batch ID
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="batchid">The ID of the batch you would like returned</param>
        /// <returns>Task of ApiResponse (MessagesResponse)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<MessagesResponse>> GetBatchByIdAsyncWithHttpInfo (string batchid)
        {
            // verify the required parameter 'batchid' is set
            if (batchid == null)
                throw new ApiException(400, "Missing required parameter 'batchid' when calling BatchMessagesApi->GetBatchById");

            var localVarPath = "/batch/{batchid}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json;charset=UTF-8"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (batchid != null) localVarPathParams.Add("batchid", Configuration.ApiClient.ParameterToString(batchid)); // path parameter

            // authentication (JWT) required
            if (!String.IsNullOrEmpty(Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetBatchById", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<MessagesResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (MessagesResponse) Configuration.ApiClient.Deserialize(localVarResponse, typeof(MessagesResponse)));
        }

        /// <summary>
        ///  Schedules a batch of SMS messages to be sent at the date time you specify
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="smsMessage">Message properties</param>
        /// <returns>ScheduledBatchResponse</returns>
        public ScheduledBatchResponse ScheduleBatch (BatchMessage smsMessage)
        {
             ApiResponse<ScheduledBatchResponse> localVarResponse = ScheduleBatchWithHttpInfo(smsMessage);
             return localVarResponse.Data;
        }

        /// <summary>
        ///  Schedules a batch of SMS messages to be sent at the date time you specify
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="smsMessage">Message properties</param>
        /// <returns>ApiResponse of ScheduledBatchResponse</returns>
        public ApiResponse< ScheduledBatchResponse > ScheduleBatchWithHttpInfo (BatchMessage smsMessage)
        {
            // verify the required parameter 'smsMessage' is set
            if (smsMessage == null)
                throw new ApiException(400, "Missing required parameter 'smsMessage' when calling BatchMessagesApi->ScheduleBatch");

            var localVarPath = "/batch/schedule";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json;charset=UTF-8"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (smsMessage != null && smsMessage.GetType() != typeof(byte[]))
            {
                localVarPostBody = Configuration.ApiClient.Serialize(smsMessage); // http body (model) parameter
            }
            else
            {
                localVarPostBody = smsMessage; // byte array
            }

            // authentication (JWT) required
            if (!String.IsNullOrEmpty(Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("ScheduleBatch", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<ScheduledBatchResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (ScheduledBatchResponse) Configuration.ApiClient.Deserialize(localVarResponse, typeof(ScheduledBatchResponse)));
        }

        /// <summary>
        ///  Schedules a batch of SMS messages to be sent at the date time you specify
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="smsMessage">Message properties</param>
        /// <returns>Task of ScheduledBatchResponse</returns>
        public async System.Threading.Tasks.Task<ScheduledBatchResponse> ScheduleBatchAsync (BatchMessage smsMessage)
        {
             ApiResponse<ScheduledBatchResponse> localVarResponse = await ScheduleBatchAsyncWithHttpInfo(smsMessage);
             return localVarResponse.Data;

        }

        /// <summary>
        ///  Schedules a batch of SMS messages to be sent at the date time you specify
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="smsMessage">Message properties</param>
        /// <returns>Task of ApiResponse (ScheduledBatchResponse)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<ScheduledBatchResponse>> ScheduleBatchAsyncWithHttpInfo (BatchMessage smsMessage)
        {
            // verify the required parameter 'smsMessage' is set
            if (smsMessage == null)
                throw new ApiException(400, "Missing required parameter 'smsMessage' when calling BatchMessagesApi->ScheduleBatch");

            var localVarPath = "/batch/schedule";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json;charset=UTF-8"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (smsMessage != null && smsMessage.GetType() != typeof(byte[]))
            {
                localVarPostBody = Configuration.ApiClient.Serialize(smsMessage); // http body (model) parameter
            }
            else
            {
                localVarPostBody = smsMessage; // byte array
            }

            // authentication (JWT) required
            if (!String.IsNullOrEmpty(Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("ScheduleBatch", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<ScheduledBatchResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (ScheduledBatchResponse) Configuration.ApiClient.Deserialize(localVarResponse, typeof(ScheduledBatchResponse)));
        }

        /// <summary>
        ///  Send a single SMS message to multiple recipients
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="smsMessage">Message properties</param>
        /// <returns>BatchMessageResponse</returns>
        public BatchMessageResponse SendBatch (BatchMessage smsMessage)
        {
             ApiResponse<BatchMessageResponse> localVarResponse = SendBatchWithHttpInfo(smsMessage);
             return localVarResponse.Data;
        }

        /// <summary>
        ///  Send a single SMS message to multiple recipients
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="smsMessage">Message properties</param>
        /// <returns>ApiResponse of BatchMessageResponse</returns>
        public ApiResponse< BatchMessageResponse > SendBatchWithHttpInfo (BatchMessage smsMessage)
        {
            // verify the required parameter 'smsMessage' is set
            if (smsMessage == null)
                throw new ApiException(400, "Missing required parameter 'smsMessage' when calling BatchMessagesApi->SendBatch");

            var localVarPath = "/batch/send";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json;charset=UTF-8"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (smsMessage != null && smsMessage.GetType() != typeof(byte[]))
            {
                localVarPostBody = Configuration.ApiClient.Serialize(smsMessage); // http body (model) parameter
            }
            else
            {
                localVarPostBody = smsMessage; // byte array
            }

            // authentication (JWT) required
            if (!String.IsNullOrEmpty(Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("SendBatch", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<BatchMessageResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (BatchMessageResponse) Configuration.ApiClient.Deserialize(localVarResponse, typeof(BatchMessageResponse)));
        }

        /// <summary>
        ///  Send a single SMS message to multiple recipients
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="smsMessage">Message properties</param>
        /// <returns>Task of BatchMessageResponse</returns>
        public async System.Threading.Tasks.Task<BatchMessageResponse> SendBatchAsync (BatchMessage smsMessage)
        {
             ApiResponse<BatchMessageResponse> localVarResponse = await SendBatchAsyncWithHttpInfo(smsMessage);
             return localVarResponse.Data;

        }

        /// <summary>
        ///  Send a single SMS message to multiple recipients
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="smsMessage">Message properties</param>
        /// <returns>Task of ApiResponse (BatchMessageResponse)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<BatchMessageResponse>> SendBatchAsyncWithHttpInfo (BatchMessage smsMessage)
        {
            // verify the required parameter 'smsMessage' is set
            if (smsMessage == null)
                throw new ApiException(400, "Missing required parameter 'smsMessage' when calling BatchMessagesApi->SendBatch");

            var localVarPath = "/batch/send";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json;charset=UTF-8"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (smsMessage != null && smsMessage.GetType() != typeof(byte[]))
            {
                localVarPostBody = Configuration.ApiClient.Serialize(smsMessage); // http body (model) parameter
            }
            else
            {
                localVarPostBody = smsMessage; // byte array
            }

            // authentication (JWT) required
            if (!String.IsNullOrEmpty(Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("SendBatch", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<BatchMessageResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (BatchMessageResponse) Configuration.ApiClient.Deserialize(localVarResponse, typeof(BatchMessageResponse)));
        }

    }
}
